### ISSUE TITLE
unable to host in linux / windows

### ISSUE THREAD

**Issue by iamherok** [Gimenz/nganu#15]
C:\Users\Das-Kun\Desktop\[bot]\nganu-master>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @adiwajshing/baileys@4.2.0
npm ERR! Found: sharp@0.28.3
npm ERR! node_modules/sharp
npm ERR!   sharp@"^0.28.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional sharp@"^0.30.5" from @adiwajshing/baileys@4.2.0
npm ERR! node_modules/@adiwajshing/baileys
npm ERR!   @adiwajshing/baileys@"github:adiwajshing/baileys" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: sharp@0.30.7
npm ERR! node_modules/sharp
npm ERR!   peerOptional sharp@"^0.30.5" from @adiwajshing/baileys@4.2.0
npm ERR!   node_modules/@adiwajshing/baileys
npm ERR!     @adiwajshing/baileys@"github:adiwajshing/baileys" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Das-Kun\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Das-Kun\AppData\Local\npm-cache\_logs\2022-06-23T10_03_13_381Z-debug-0.log

C:\Users\Das-Kun\Desktop\[bot]\nganu-master>

**Comment by Gimenz** [comment]
try install use --force args, example npm i --force
if still facing same issue, try remove sharp from package.json

or wait a few days, i will update with many fixes
Regards.

**Comment by iamherok** [comment]
> try install use --force args, example npm i --force if still facing same issue, try remove sharp from package.json
> 
> or wait a few days, i will update with many fixes Regards.

Ohh ok
